[project]
name = "ytrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "avinash874", email = "avinashsingh09072004@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "faiss-cpu>=1.15.0",
    "ipykernel>=7.3.0",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.1",
    "pymupdf>=1.28.2",
    "pypdf>=6.17.0",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
ytrag = "ytrag:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
